/**
 * PE CLUSTER · Google Form + scoring spreadsheet builder
 * Generated by pe-cluster-builder/scripts/make_form_script.py from content.json.
 * Do not edit the SPEC block by hand: change content.json and regenerate, or the
 * scoring sheet .docx and this workbook will drift apart.
 *
 * Builds:
 *   1. The student-facing Google Form (quiz mode, one item per criterion)
 *   2. A linked scoring spreadsheet that auto-scores the selected-response criteria,
 *      accepts 0/1 entry for the constructed-response criteria, and rolls each bucket
 *      up to a 1-4 level using gates derived from each bucket's criterion count.
 *
 * HOW TO RUN
 *   script.google.com -> New project -> paste this file -> Save
 *   Upload the stimulus PNGs to Drive first, with the exact names in CONFIG.images.
 *   Run -> buildAssessment -> authorise when prompted.
 *   The execution log prints the Form edit URL, the live URL and the Sheet URL.
 *
 * Re-running creates a fresh Form and Sheet. It never modifies an existing one.
 *
 * DESIGN NOTES worth keeping when you edit this file
 *   - CRITERIA is the single source of truth. The scoring sheet .docx must be generated
 *     from the same source, or the two drift. That has happened before.
 *   - Answer keys live in the hidden _key sheet. Scoring formulas reference those cells,
 *     so re-wording an option in the Form means editing one cell, not 400 formulas.
 *   - Header cells that look like ranges are written as text. "1-4" left as a plain value
 *     is silently converted by Sheets into a date.
 *   - Quiz grade release cannot be set from Apps Script. Quizzes default to manual
 *     release, which is what we want. Do not add a config flag implying otherwise.
 */

/* ============================================================ *
 *  CONFIGURATION
 * ============================================================ */

/* >>> SPEC BEGIN (generated) */

var CONFIG = {
  pe: 'HS-PSx-x',
  formTitle: 'Unit x Assessment · <short context title>',
  sheetTitle: 'Unit x · Scoring (HS-PSx-x)',
  durationNote: 'Suggested time: 40 minutes.',
  collectEmails: true,      // false if students are not signed in

  /* Section 1 identity block. Teachers appear as a dropdown; edit this list per section
   * roster. The access code gates entry: change the codeword to re-open or close the
   * form without rebuilding it. Treat it as a soft gate on casual sharing, not as
   * security: the pattern travels with the published form and a determined student
   * can read it. Rotate it between blocks if that matters. */
  teachers: ['<Teacher One>', '<Teacher Two>'],
  accessCode: '<CODEWORD>',
  accessCodeHelp: 'Enter the code your teacher gives you at the start of the period.',
  nameHelp: 'First and last name, as it appears on your class list.',

  /* Upload these to Drive before running. Missing files fall back to the text
   * version of the same stimulus, so the build degrades rather than fails. */
  images: {
    // key: 'U1-PA-F01-descriptive-name.png'
  }
};

/* ============================================================ *
 *  STIMULUS
 *  Keep every value a student needs in here. No item may depend on
 *  anything that lives only in the unit's slides or notes.
 * ============================================================ */

var CONTEXT_BLURB =
  '<Whose investigation this is, what they measured, and what the student is being ' +
  'asked to do with it. State plainly that the student did not run it.>\n\n' +
  'Resources allowed: <list>. No AI assistants. ' + CONFIG.durationNote;

var GLOSSARY =
  'TERMS USED IN THIS ASSESSMENT\n\n' +
  '<term>: <plain-language definition that does not give away any answer>\n' +
  '<term>: <definition>';

var STIMULUS = [
  // One entry per table or figure, in the order students meet them.
  // fallback is what students see if the image is missing from Drive, so it must be
  // complete enough to answer the items on its own.
  // { key: 'evaporation', title: 'Table 1. <caption>', fallback: '<full text version>' }
];

/* ============================================================ *
 *  EVIDENCE STATEMENT FEATURES
 *  Every in-scope observable feature, verbatim enough to be recognised.
 *  Each must be assessed once or twice. Out-of-scope features (no skill
 *  code on the course scope list) are excluded here, not later.
 * ============================================================ */

var FEATURES = [
  // 'Components: <observable feature text>',
  // 'Relationships: <observable feature text>',
  // 'Connections: <observable feature text>'
];

/* ============================================================ *
 *  BUCKETS
 *  Every bucket the PE maps to. Criterion counts come from the evidence
 *  statement and will be uneven. Gates are derived from the counts below.
 * ============================================================ */

var BUCKETS = [
  {
    name: 'DCI.x',
    label: 'DCI.x <bucket title>',
    crits: ['C1', 'C2', 'C3', 'C4'],   // evidence-statement criteria; count comes from the statement
    mwdCrit: 'C5',                     // the beyond-statement probe for THIS bucket, scored 0/1
    reflection: '<Which pair of criteria should separate students, and what a class-wide ' +
                'result on that pair says about instruction.>'
  }
  // ... one entry per bucket. Every bucket has exactly one mwdCrit.
];

/* Distinction rule.
 * false (default): Meeting gate met AND the bucket's MwD criterion earned  ->  4
 * true:            the 85% raw gate met AND the MwD criterion earned       ->  4
 * The stricter setting stops Distinction being reachable from a bare Meeting score. */
var MWD_REQUIRES_TOP_GATE = false;

/* 'probe' (default): one beyond-statement probe per bucket, as above.
 * 'perfect': a full raw score in a bucket awards 4; no probes.
 * 'none': this instrument reports levels up to 3; no probes. */
var DISTINCTION_MODE = 'probe';

/* ============================================================ *
 *  CRITERIA
 *  Criterion IDs run in BUCKET order. Item order is student order.
 *  The two differ, and that is correct.
 * ============================================================ */

var CRITERIA = [
  {
    crit: 'C1',
    buckets: ['DCI.x'],          // several tags = cross-scored: scored once, counted in each
    skill: 'PSx-x.x',            // must exist on the course scope list
    feature: '<the FEATURES entry this criterion assesses>',
    order: 1,   // part (a) of the item                    // position in the student's item sequence
    type: 'mc',                  // 'mc' auto-scored, 'para' hand-scored
    title: 'Q1. <short item title>',
    stem: '<The question. Task verb first. Roughly 25 words or fewer.>',
    help: '<Where to look, or a term gloss. Empty string if none.>',
    part: 1,                     // page break group; see PARTS below
    criterion: '<Full criterion text for the scoring sheet. Self-contained.>',
    earns: '<What earns the point, in the marker\'s words.>',
    choices: [
      ['<key, matched in length to the distractors>', true, ''],
      ['<distractor>', false, 'misconception: <name it>'],
      ['<distractor>', false, 'misconception: <name it>'],
      ['<distractor>', false, 'misconception: <name it>']
    ]
  },
  {
    crit: 'C6',
    buckets: ['CCC.x', 'SEP.x'], // cross-scored; criterion text must name both demands
    skill: 'PSx-x.x',
    feature: '<the FEATURES entry this criterion assesses>',
    order: 8,
    type: 'para',
    title: 'Q8. <short item title>',
    stem: '<The question.>',
    help: 'Cite specific values from the tables. Three or four sentences.',
    part: 2,
    criterion: '<Full criterion text.>',
    earns: '<What earns the point.>'
  },
  {
    /* MwD probe. Written as part (b) of an item that already exists in this bucket,
     * so it extends reasoning the student has just done rather than opening a new task.
     * Scored 0/1 like any other criterion, but kept out of the bucket's raw score. */
    crit: 'C5',
    buckets: ['DCI.x'],          // exactly one bucket; MwD probes are never cross-scored
    skill: 'PSx-x.x',
    beyond: true,
    extends: '<the FEATURES entry this probe goes past>',
    order: 2,                    // sits directly after the part (a) item it extends
    type: 'para',
    title: 'Q2b. <short item title>',
    stem: '<The push past the evidence statement. Two sentences.>',
    help: 'Two sentences is enough.',
    part: 1,
    criterion: '<Full criterion text for the beyond-statement performance.>',
    earns: '<What earns the point. Must be as concrete as any other criterion.>'
  }
  // ... one entry per criterion
];

var PARTS = [
  { n: 1, title: 'Part 1 · <name>', help: 'The tables are on the previous page if you need to scroll back.' },
  { n: 2, title: 'Part 2 · <name>', help: 'Written responses. Cite values from the tables wherever you can.' }
];

/* Minimum criteria per bucket, agreed with the user at Phase 0.
 * Below this a bucket's gate stops distinguishing anything. Set it before building. */
var MIN_ITEMS_PER_BUCKET = 3;

/* Scoring sheet layout: Timestamp, Name, Block, Teacher occupy columns 1-4. */
var FIRST_CRIT_COL_GLOBAL = 5;
/* <<< SPEC END */

/* ============================================================ *
 *  SPEC VALIDATION
 *  Runs before anything is created. A bad spec fails here, loudly,
 *  rather than producing a Form that scores wrongly.
 * ============================================================ */

function validateSpec_() {
  var errors = [], warnings = [];

  BUCKETS.forEach(function (b) {
    if (b.crits.length === 0) {
      errors.push(b.name + ' has no evidence-statement criteria.');
    } else if (b.crits.length < MIN_ITEMS_PER_BUCKET) {
      warnings.push(b.name + ' has ' + b.crits.length + ' evidence-statement criteria, below the ' +
                    'floor of ' + MIN_ITEMS_PER_BUCKET + '. Raise it before building, do not pad it.');
    }
    b.crits.forEach(function (k) {
      if (!CRITERIA.some(function (c) { return c.crit === k; })) {
        errors.push(b.name + ' lists ' + k + ', which is not in CRITERIA.');
      }
    });

    // Exactly one MwD probe per bucket in 'probe' mode; none otherwise.
    if (DISTINCTION_MODE !== 'probe') {
      if (b.mwdCrit) errors.push(b.name + ' names a probe but DISTINCTION_MODE is ' + DISTINCTION_MODE + '.');
    } else if (!b.mwdCrit) {
      errors.push(b.name + ' has no mwdCrit. Every bucket needs one beyond-statement probe.');
    } else {
      var m = CRITERIA.filter(function (c) { return c.crit === b.mwdCrit; })[0];
      if (!m) errors.push(b.name + ' names MwD probe ' + b.mwdCrit + ', which is not in CRITERIA.');
      else {
        if (!m.beyond) errors.push(b.mwdCrit + ' is the MwD probe for ' + b.name +
                                   ' but is not flagged beyond: true.');
        if ((m.buckets || []).length !== 1 || m.buckets[0] !== b.name) {
          errors.push(b.mwdCrit + ' must be tagged to exactly one bucket, ' + b.name +
                      '. MwD probes are never cross-scored.');
        }
        if (b.crits.indexOf(b.mwdCrit) >= 0) {
          errors.push(b.mwdCrit + ' appears in ' + b.name + '.crits. The MwD probe sits outside ' +
                      'the raw score and must not be listed there.');
        }
      }
    }
    if (!b.reflection) errors.push(b.name + ' has no grading reflection entry.');

    // Exclusivity is judged on evidence-statement criteria only.
    var exclusive = b.crits.filter(function (k) { return bucketsFor_(k).length === 1; }).length;
    var need = Math.max(2, Math.ceil(b.crits.length / 2));
    if (b.crits.length >= 2 && exclusive < need) {
      errors.push(b.name + ' has ' + exclusive + ' exclusive criteria; needs at least ' + need +
                  '. A bucket populated mostly by shared judgments is not independently measured.');
    }
  });

  CRITERIA.forEach(function (c) {
    var tags = c.buckets || [];
    if (!tags.length) errors.push(c.crit + ' carries no bucket tag.');
    tags.forEach(function (t) {
      var b = BUCKETS.filter(function (x) { return x.name === t; })[0];
      if (!b) errors.push(c.crit + ' is tagged ' + t + ', which is not a bucket.');
      else if (b.crits.indexOf(c.crit) < 0 && b.mwdCrit !== c.crit) {
        errors.push(c.crit + ' is tagged ' + t + ' but ' + t + ' neither lists it in crits nor ' +
                    'names it as mwdCrit.');
      }
    });
    if (tags.length >= 3) {
      warnings.push(c.crit + ' is tagged to ' + tags.length + ' buckets. Must be listed in the ' +
                    'draft open decisions and approved, not inherited.');
    }

    // Every criterion is anchored: an evidence statement feature, or a declared push past one.
    if (c.beyond) {
      if (c.feature) errors.push(c.crit + ' is beyond-statement and must not also claim a feature.');
      if (!c.extends) errors.push(c.crit + ' is beyond-statement but names no feature it extends.');
      else if (FEATURES.indexOf(c.extends) < 0) {
        errors.push(c.crit + ' extends a feature not in FEATURES: ' + c.extends);
      }
      if (!BUCKETS.some(function (b) { return b.mwdCrit === c.crit; })) {
        errors.push(c.crit + ' is flagged beyond: true but is not the MwD probe for any bucket. ' +
                    'Beyond-statement criteria exist only to determine Distinction.');
      }
    } else if (!c.feature) {
      errors.push(c.crit + ' is anchored to nothing. Every criterion assesses an evidence ' +
                  'statement feature, or is a declared beyond-statement probe.');
    } else if (FEATURES.indexOf(c.feature) < 0) {
      errors.push(c.crit + ' cites a feature not in FEATURES: ' + c.feature);
    }

    if (!c.skill) errors.push(c.crit + ' carries no skill code.');
    if (!c.criterion) errors.push(c.crit + ' has no criterion text.');
    if (!c.earns) errors.push(c.crit + ' has no what-earns-the-point entry.');
  });

  // Evidence statement coverage: every feature once or twice, never more.
  var byFeature = {};
  CRITERIA.forEach(function (c) {
    if (c.beyond || !c.feature) return;
    (byFeature[c.feature] = byFeature[c.feature] || []).push(c.crit);
  });
  FEATURES.forEach(function (f) {
    var hits = byFeature[f] || [];
    if (hits.length === 0) errors.push('Evidence feature not assessed: ' + f);
    else if (hits.length > 2) {
      errors.push('Evidence feature assessed ' + hits.length + ' times (' + hits.join(', ') +
                  '): ' + f);
    }
  });

  // One item per criterion.
  var seenTitle = {}, seenOrder = {};
  CRITERIA.forEach(function (c) {
    if (seenTitle[c.title]) errors.push('Duplicate item title: ' + c.title);
    if (seenOrder[c.order]) errors.push('Duplicate item order: ' + c.order);
    seenTitle[c.title] = true;
    seenOrder[c.order] = true;
  });

  // Selected-response items.
  CRITERIA.filter(function (c) { return c.type === 'mc'; }).forEach(function (c) {
    var keys = (c.choices || []).filter(function (ch) { return ch[1]; });
    if (keys.length !== 1) errors.push(c.crit + ' has ' + keys.length + ' correct options; must be 1.');
    var lens = (c.choices || []).map(function (ch) { return ch[0].split(/\s+/).length; });
    var max = Math.max.apply(null, lens), min = Math.min.apply(null, lens);
    if (max - min > 8) {
      errors.push(c.crit + ' option lengths span ' + min + ' to ' + max +
                  ' words. A key that is visibly longest is answerable without the science.');
    }
    (c.choices || []).forEach(function (ch) {
      if (!ch[1] && !ch[2]) errors.push(c.crit + ' has a distractor with no named misconception.');
    });
  });

  // Key position must be distributed. A key that is always option A is answerable
  // without reading the stem, and generated item sets drift to A unless checked.
  var mc = CRITERIA.filter(function (c) { return c.type === 'mc'; });
  if (mc.length >= 3) {
    var pos = {}, letters = 'ABCDEFGH';
    mc.forEach(function (c) {
      var i = c.choices.findIndex(function (ch) { return ch[1]; });
      var L = letters[i] || ('#' + i);
      (pos[L] = pos[L] || []).push(c.crit);
    });
    var used = Object.keys(pos);
    var biggest = used.reduce(function (a, b) {
      return pos[a].length >= pos[b].length ? a : b;
    });
    var cap = Math.max(2, Math.ceil(mc.length / 2));
    if (used.length === 1) {
      errors.push('Every selected-response key is option ' + used[0] + '. Distribute the keys.');
    } else if (pos[biggest].length > cap) {
      errors.push('Option ' + biggest + ' is the key on ' + pos[biggest].length + ' of ' +
                  mc.length + ' selected-response items (' + pos[biggest].join(', ') +
                  '); cap is ' + cap + '. Distribute the keys.');
    }
    if (mc.length >= 4 && used.length < 3) {
      errors.push('Selected-response keys occupy only ' + used.length + ' option positions (' +
                  used.join(', ') + '). Use at least three across the set.');
    }
    Logger.log('Key positions: ' + used.sort().map(function (L) {
      return L + '=' + pos[L].length;
    }).join(' '));
  }

  // Section 1 configuration.
  if (!CONFIG.teachers || !CONFIG.teachers.length) {
    errors.push('CONFIG.teachers is empty. The Teacher dropdown needs a roster.');
  }
  (CONFIG.teachers || []).forEach(function (t) {
    if (/^<.*>$/.test(t)) errors.push('CONFIG.teachers still holds the placeholder ' + t + '.');
  });
  if (!CONFIG.accessCode || /^<.*>$/.test(CONFIG.accessCode)) {
    errors.push('CONFIG.accessCode is unset or still the placeholder.');
  }

  // Time budget.
  if (CRITERIA.length > 13) {
    warnings.push(CRITERIA.length + ' scored judgments exceeds the ~40 minute budget of about 13 ' +
                  '(roughly 9-10 evidence-statement items plus one MwD probe per bucket). Raise it ' +
                  'with the teacher at the draft stage; do not compress the items.');
  }

  warnings.forEach(function (w) { Logger.log('WARNING: ' + w); });
  if (errors.length) {
    throw new Error('Spec validation failed:\n  - ' + errors.join('\n  - '));
  }
  Logger.log('Spec OK: ' + CRITERIA.length + ' criteria across ' + BUCKETS.length + ' buckets (' +
             BUCKETS.map(function (b) {
               return b.name + ' ' + b.crits.length + (b.mwdCrit ? '+MwD' : '');
             }).join(', ') + ').');
}

/* ============================================================ *
 *  SCORE GATES: derived per bucket from its EVIDENCE-STATEMENT criterion
 *  count. The MwD probe sits outside the raw score: it is the gate condition,
 *  not a point toward it, so a student who meets every feature and skips the
 *  beyond-statement item still lands at Meeting.
 *  Proportions from scoring-sheet-design.md 4D: Developing ~45%,
 *  Meeting ~70%, MwD ~85% plus the Consideration. Emerging is any
 *  raw score of 1 or more; NYE is 0 only. Where the Meeting and MwD
 *  floors coincide, Meeting is that score without the Consideration.
 * ============================================================ */

function gatesFor_(n) {
  return {
    n: n,
    emerging: 1,
    developing: Math.ceil(0.45 * n),
    meeting: Math.ceil(0.70 * n),
    mwd: Math.max(Math.ceil(0.85 * n), Math.ceil(0.70 * n))
  };
}

/* ============================================================ *
 *  MAIN
 * ============================================================ */

function buildAssessment() {
  validateSpec_();

  var ss = SpreadsheetApp.create(CONFIG.sheetTitle);
  var form = FormApp.create(CONFIG.formTitle);

  form.setDescription(CONTEXT_BLURB);
  form.setIsQuiz(true);
  form.setCollectEmail(CONFIG.collectEmails);
  form.setShuffleQuestions(false);
  // Google Forms cannot shuffle options from Apps Script, so key position is not
  // randomised at run time. Distributing the keys in the spec is the only control.
  form.setProgressBar(true);
  form.setAllowResponseEdits(false);
  form.setLimitOneResponsePerUser(true);

  buildSectionOne_(form);

  // Stimulus pages
  form.addPageBreakItem()
    .setTitle('Before you start')
    .setHelpText('Read this page before answering anything. You can scroll back to it.');
  form.addSectionHeaderItem().setTitle('Terms used').setHelpText(GLOSSARY);

  if (STIMULUS.length) {
    form.addPageBreakItem().setTitle('The information you have');
    STIMULUS.forEach(function (s) {
      addStimulus_(form, s.title, CONFIG.images[s.key], s.fallback);
    });
  }

  // Items, in student order, grouped into parts
  var ordered = CRITERIA.slice().sort(function (a, b) { return a.order - b.order; });
  var currentPart = null;
  ordered.forEach(function (spec) {
    if (spec.part !== currentPart) {
      var p = PARTS.filter(function (x) { return x.n === spec.part; })[0];
      form.addPageBreakItem()
        .setTitle(p ? p.title : 'Part ' + spec.part)
        .setHelpText(p ? p.help : '');
      currentPart = spec.part;
    }
    if (spec.type === 'mc') addMultipleChoice_(form, spec);
    else addParagraph_(form, spec);
  });

  form.setDestination(FormApp.DestinationType.SPREADSHEET, ss.getId());
  SpreadsheetApp.flush();

  buildKeySheet_(ss);       // must run first: the scoring formulas reference it
  buildScoringSheet_(ss);
  buildReferenceSheet_(ss);
  buildFeaturesAnalysis_(ss);
  buildStudentFeatureGrid_(ss);

  var def = ss.getSheetByName('Sheet1');
  if (def) ss.deleteSheet(def);

  Logger.log('FORM (edit):    ' + form.getEditUrl());
  Logger.log('FORM (student): ' + form.getPublishedUrl());
  Logger.log('SCORING SHEET:  ' + ss.getUrl());
}

/* ============================================================ *
 *  SECTION 1: identity and access
 * ============================================================ */

function buildSectionOne_(form) {
  form.addTextItem()
    .setTitle('Name')
    .setHelpText(CONFIG.nameHelp || 'First and last name.')
    .setRequired(true);

  form.addTextItem()
    .setTitle('Block')
    .setRequired(true);

  form.addListItem()
    .setTitle('Teacher')
    .setChoiceValues(CONFIG.teachers)
    .setRequired(true);

  var code = FormApp.createTextValidation()
    .setHelpText('That is not the code for this assessment.')
    .requireTextMatchesPattern('(?i)^\\s*' + escapeRegex_(CONFIG.accessCode) + '\\s*$')
    .build();

  form.addTextItem()
    .setTitle('Access code')
    .setHelpText(CONFIG.accessCodeHelp)
    .setValidation(code)
    .setRequired(true);
}

/* RE2 metacharacter escape, so a codeword containing . or - still matches literally. */
function escapeRegex_(t) {
  return String(t).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/* ============================================================ *
 *  ITEM BUILDERS
 * ============================================================ */

function addMultipleChoice_(form, spec) {
  var item = form.addMultipleChoiceItem();
  var choices = spec.choices.map(function (c) { return item.createChoice(c[0], c[1]); });
  item.setTitle(spec.title)
      .setHelpText(buildHelp_(spec))
      .setChoices(choices)
      .setPoints(1)
      .setRequired(true);
  item.setFeedbackForIncorrect(
    FormApp.createFeedback().setText('Review this one with the data in front of you.').build()
  );
  return item;
}

function addParagraph_(form, spec) {
  return form.addParagraphTextItem()
    .setTitle(spec.title)
    .setHelpText(buildHelp_(spec))
    .setPoints(1)
    .setRequired(true);
}

function buildHelp_(spec) {
  return [spec.stem, spec.help].filter(function (x) { return x; }).join('\n\n');
}

function imageBlob_(name) {
  if (!name) return null;
  try {
    var it = DriveApp.getFilesByName(name);
    if (!it.hasNext()) { Logger.log('image not found in Drive: ' + name); return null; }
    return it.next().getBlob();
  } catch (e) {
    Logger.log('image lookup failed for ' + name + ': ' + e);
    return null;
  }
}

function addStimulus_(form, title, imageName, fallbackText) {
  var blob = imageBlob_(imageName);
  if (blob) {
    form.addImageItem().setTitle(title).setImage(blob)
        .setWidth(640).setAlignment(FormApp.Alignment.LEFT);
  } else {
    form.addSectionHeaderItem().setTitle(title).setHelpText(fallbackText);
  }
}

/* ============================================================ *
 *  KEY SHEET (hidden)
 *  One row per criterion. The scoring formulas resolve the answer key
 *  through column C here, so re-wording an option means editing one cell.
 * ============================================================ */

function buildKeySheet_(ss) {
  var sh = ss.insertSheet('_key');
  var rows = [['Crit', 'Item title', 'Key text', 'Type']];
  critOrder_().forEach(function (k) {
    var s = specFor_(k);
    rows.push([k, s.title, s.type === 'mc' ? correctChoice_(s) : '', s.type]);
  });
  sh.getRange(1, 1, rows.length, 4).setValues(rows);
  sh.getRange(1, 1, 1, 4).setFontWeight('bold');
  sh.setColumnWidth(2, 240);
  sh.setColumnWidth(3, 520);
  sh.hideSheet();
}

/* Row in _key for a given criterion, 1-indexed with the header row. */
function keyRow_(crit) {
  return critOrder_().indexOf(crit) + 2;
}

/* ============================================================ *
 *  SCORING SHEET
 * ============================================================ */

function buildScoringSheet_(ss) {
  var sh = ss.insertSheet('Scoring');
  var RESP = "'Form Responses 1'";
  var LASTROW = 400;
  var order = critOrder_();

  var FIRST_CRIT_COL = FIRST_CRIT_COL_GLOBAL;   // Timestamp, Name, Block, Teacher occupy 1-4
  var head1 = ['', '', '', ''];
  var head2 = ['Timestamp', 'Name', 'Block', 'Teacher'];
  var head3 = ['', '', '', ''];

  order.forEach(function (k) {
    var s = specFor_(k);
    head1.push(s.buckets.join(' '));
    head2.push(k);
    head3.push((s.type === 'mc' ? 'auto · ' : 'HAND · ') + s.skill);
  });
  BUCKETS.forEach(function (b) {
    head1.push(b.name, b.name, b.name);
    head2.push('raw', 'MwD', 'LEVEL');
    head3.push('/' + b.crits.length + ' ES', b.mwdCrit || DISTINCTION_MODE, '1-4');
  });

  // Force the header block to plain text BEFORE writing, or Sheets converts
  // values like "1-4" and "0-1" into dates.
  sh.getRange(1, 1, 3, head1.length).setNumberFormat('@');
  sh.getRange(1, 1, 1, head1.length).setValues([head1]);
  sh.getRange(2, 1, 1, head2.length).setValues([head2]);
  sh.getRange(3, 1, 1, head3.length).setValues([head3]);

  var firstDataRow = 4;
  var rows = [];
  for (var r = firstDataRow; r <= LASTROW; r++) {
    var respRow = r - firstDataRow + 2;
    var row = [];

    row.push('=IFERROR(' + RESP + '!A' + respRow + ',"")');
    row.push(pull_(RESP, respRow, 'Name'));
    row.push(pull_(RESP, respRow, 'Block'));
    row.push(pull_(RESP, respRow, 'Teacher'));

    order.forEach(function (k) {
      var s = specFor_(k);
      if (s.type === 'mc') {
        row.push('=IF($B' + r + '="","",IF(EXACT(' +
                 pullExpr_(RESP, respRow, s.title) + ',_key!$C$' + keyRow_(k) + '),1,0))');
      } else {
        row.push('');   // teacher enters 0 or 1
      }
    });

    BUCKETS.forEach(function (b, idx) {
      var cols = b.crits.map(function (k) { return colLetter_(FIRST_CRIT_COL + order.indexOf(k)) + r; });
      var rawCol = colLetter_(FIRST_CRIT_COL + order.length + idx * 3);
      var mwdCol = colLetter_(FIRST_CRIT_COL + order.length + idx * 3 + 1);
      var g = gatesFor_(b.crits.length);
      var promoteAt = MWD_REQUIRES_TOP_GATE ? g.mwd : g.meeting;
      row.push('=IF($B' + r + '="","",SUM(' + cols.join(',') + '))');
      // The bucket's MwD probe score, mirrored from its own criterion column.
      row.push(b.mwdCrit ? '=IF($B' + r + '="","",' + colLetter_(FIRST_CRIT_COL + order.indexOf(b.mwdCrit)) + r + ')' : '');
      // Distinction modifies, it never shortcuts: the gate level must be reached first.
      var four = DISTINCTION_MODE === 'probe'
        ? 'IF(AND(' + rawCol + r + '>=' + promoteAt + ',' + mwdCol + r + '=1),4,'
        : DISTINCTION_MODE === 'perfect' ? 'IF(' + rawCol + r + '>=' + b.crits.length + ',4,' : 'IF(FALSE,4,';
      row.push('=IF($B' + r + '="","",' + four +
               'IF(' + rawCol + r + '>=' + g.meeting + ',3,' +
               'IF(' + rawCol + r + '>=' + g.developing + ',2,' +
               'IF(' + rawCol + r + '>=' + g.emerging + ',1,"NYE")))))');
    });

    rows.push(row);
  }
  sh.getRange(firstDataRow, 1, rows.length, rows[0].length).setValues(rows);

  sh.setFrozenRows(3);
  sh.setFrozenColumns(4);
  sh.getRange(1, 1, 3, head1.length).setFontWeight('bold').setWrap(true)
    .setBackground('#1F3864').setFontColor('#FFFFFF');

  var zeroOne = SpreadsheetApp.newDataValidation()
    .requireNumberBetween(0, 1).setAllowInvalid(false)
    .setHelpText('Enter 0 or 1.').build();
  order.forEach(function (k, i) {
    if (specFor_(k).type !== 'mc') {
      sh.getRange(firstDataRow, FIRST_CRIT_COL + i, LASTROW - firstDataRow + 1, 1)
        .setDataValidation(zeroOne).setBackground('#FFF2CC');
    }
  });

  BUCKETS.forEach(function (b, idx) {
    var mwdCol = FIRST_CRIT_COL + order.length + idx * 3 + 1;
    sh.getRange(firstDataRow, mwdCol, LASTROW - firstDataRow + 1, 1)
      .setHorizontalAlignment('center').setBackground('#FCE4D6');
    sh.getRange(firstDataRow, mwdCol + 1, LASTROW - firstDataRow + 1, 1)
      .setFontWeight('bold').setHorizontalAlignment('center').setBackground('#E2EFDA');
  });

  sh.autoResizeColumns(1, 4);
  for (var w = FIRST_CRIT_COL; w <= head1.length; w++) sh.setColumnWidth(w, 62);
}

/* ============================================================ *
 *  REFERENCE SHEET: criteria, gates, Considerations, reflection
 *  Every string here comes from CRITERIA and BUCKETS. Nothing is retyped.
 * ============================================================ */

function buildReferenceSheet_(ss) {
  var sh = ss.insertSheet('Key & Gates');
  var out = [];

  out.push([CONFIG.formTitle + ' · ' + CONFIG.pe + ' · criterion key']);
  out.push([]);
  out.push(['Crit', 'Bucket', 'Skill', 'Item', 'Scoring', 'What earns the point']);

  critOrder_().forEach(function (k) {
    var s = specFor_(k);
    out.push([k, s.buckets.join(', '), s.skill, s.title.split('.')[0],
              s.type === 'mc' ? 'auto' : 'hand', s.earns]);
  });

  out.push([]);
  out.push(['Score gates · derived from each bucket\u2019s criterion count']);
  out.push(['Bucket', 'ES items', 'Emerging 1', 'Developing 2', 'Meeting 3', 'MwD 4']);
  BUCKETS.forEach(function (b) {
    var g = gatesFor_(b.crits.length);
    out.push([b.name, String(b.crits.length), String(g.emerging) + '+',
              String(g.developing) + '+', String(g.meeting) + '+',
              DISTINCTION_MODE === 'probe'
                ? String(MWD_REQUIRES_TOP_GATE ? g.mwd : g.meeting) + '+ and ' + b.mwdCrit + ' earned'
                : DISTINCTION_MODE === 'perfect' ? String(g.n) + ' of ' + g.n + ' (full raw score awards 4)'
                : 'not awarded on this instrument']);
  });
  out.push(['', '', 'Raw 0 is NYE. The raw score counts evidence-statement criteria only; the ' +
            'MwD probe is scored separately and promotes a student who has already reached the ' +
            'gate above.']);
  out.push(['', '', 'A cross-scored criterion counts toward the raw score of every bucket it is ' +
            'tagged to, so one score can appear in more than one column.']);

  out.push([]);
  out.push(['Meeting with Distinction probes']);
  out.push(['Bucket', 'Criterion', 'Item', 'What earns the point']);
  BUCKETS.filter(function (b) { return b.mwdCrit; }).forEach(function (b) {
    var m = specFor_(b.mwdCrit);
    out.push([b.name, b.mwdCrit, m.title.split('.')[0], m.earns]);
  });
  out.push(['', '', 'Distinction is directly asked and directly scored. It is not a judgment ' +
            'about whether a student went beyond unprompted, and it never lifts a student who ' +
            'has not first reached the Meeting gate on the evidence-statement criteria.']);

  out.push([]);
  out.push(['Grading reflection']);
  BUCKETS.forEach(function (b) { out.push([b.name, b.reflection]); });

  out.push([]);
  out.push(['Follow-through', 'A student who reaches a wrong value early and reasons correctly ' +
            'from that wrong value loses the criterion where the error occurred, not every ' +
            'criterion downstream of it.']);
  out.push(['Accumulation', 'Bucket levels accumulate across the reporting period. A level ' +
            'earned here does not overwrite a higher level already earned for the same bucket ' +
            'on another assessment.']);

  sh.getRange(1, 1, out.length, 6).setValues(
    out.map(function (r) { while (r.length < 6) r.push(''); return r; })
  );
  sh.getRange(1, 1, 1, 6).setFontWeight('bold').setFontSize(12);
  sh.getRange(3, 1, 1, 6).setFontWeight('bold').setBackground('#1F3864').setFontColor('#FFFFFF');
  sh.setColumnWidth(6, 520);
  sh.getRange(1, 1, out.length, 6).setWrap(true).setVerticalAlignment('top');
}

/* ============================================================ *
 *  FEATURES ANALYSIS
 *  Live off the Scoring sheet, so it fills in as hand-scoring proceeds.
 *  Read after grading; Key & Gates is what a marker reads during it.
 * ============================================================ */

var ANALYSIS_FIRST_ROW = 4;
var ANALYSIS_LAST_ROW = 400;

/* A1-style range on the Scoring sheet for one criterion's column. */
function scoreRange_(crit) {
  var col = colLetter_(FIRST_CRIT_COL_GLOBAL + critOrder_().indexOf(crit));
  return "'Scoring'!" + col + ANALYSIS_FIRST_ROW + ':' + col + ANALYSIS_LAST_ROW;
}

function levelRange_(bucketIdx) {
  var col = colLetter_(FIRST_CRIT_COL_GLOBAL + critOrder_().length + bucketIdx * 3 + 2);
  return "'Scoring'!" + col + ANALYSIS_FIRST_ROW + ':' + col + ANALYSIS_LAST_ROW;
}

function teacherRange_() {
  return "'Scoring'!$D$" + ANALYSIS_FIRST_ROW + ':$D$' + ANALYSIS_LAST_ROW;
}

function buildFeaturesAnalysis_(ss) {
  var sh = ss.insertSheet('Features Analysis');
  var rows = [], r = 0;
  function put(a) { rows.push(a); r++; return r; }

  put(['Features Analysis · ' + CONFIG.pe]);
  put(['Percentages are the share of scored responses earning the criterion. ' +
       'Blank cells mean not yet scored.']);
  put([]);

  // --- Per feature -------------------------------------------------------
  put(['EVIDENCE STATEMENT FEATURES']);
  put(['Feature', 'Buckets', 'Criteria', 'n scored', 'Crit 1 %', 'Crit 2 %',
       'Feature %', 'Flag']);
  var featureFirstRow = r + 1;

  FEATURES.forEach(function (f) {
    var crits = CRITERIA.filter(function (c) { return !c.beyond && c.feature === f; })
                        .map(function (c) { return c.crit; });
    var buckets = {};
    crits.forEach(function (k) { bucketsFor_(k).forEach(function (b) { buckets[b] = 1; }); });

    var pcts = crits.map(function (k) {
      return '=IFERROR(AVERAGE(' + scoreRange_(k) + '),"")';
    });
    while (pcts.length < 2) pcts.push('');

    var n = crits.length
      ? '=COUNT(' + scoreRange_(crits[0]) + ')'
      : 0;

    var featurePct = crits.length
      ? '=IFERROR(AVERAGE(' + crits.map(scoreRange_).join(',') + '),"")'
      : '';

    var row = r + 1;
    var flag = crits.length > 1
      ? '=IF(OR(E' + row + '="",F' + row + '=""),"",IF(ABS(E' + row + '-F' + row + ')>0.3,' +
        '"CHECK ITEMS: same feature, ' + '"&TEXT(ABS(E' + row + '-F' + row + '),"0%")&" apart",""))'
      : '';

    put([f, Object.keys(buckets).join(', '), crits.join(', '), n,
         pcts[0], pcts[1], featurePct, flag]);
  });
  var featureLastRow = r;

  put([]);

  // --- MwD probes, reported apart from coverage --------------------------
  put(['MEETING WITH DISTINCTION PROBES']);
  put(['These sit outside the evidence statement by design. A low percentage here is a hard ' +
       'question working as intended, not a coverage gap.']);
  put(['Bucket', 'Criterion', 'Extends feature', 'n scored', '% earning']);
  BUCKETS.filter(function (b) { return b.mwdCrit; }).forEach(function (b) {
    var m = specFor_(b.mwdCrit);
    put([b.name, b.mwdCrit, m.extends || '', '=COUNT(' + scoreRange_(b.mwdCrit) + ')',
         '=IFERROR(AVERAGE(' + scoreRange_(b.mwdCrit) + '),"")']);
  });

  put([]);

  // --- Bucket level distribution ----------------------------------------
  put(['BUCKET LEVEL DISTRIBUTION']);
  put(['Bucket', 'NYE', '1', '2', '3', '4', 'Meeting or above']);
  BUCKETS.forEach(function (b, i) {
    var lr = levelRange_(i);
    put([b.name,
         '=COUNTIF(' + lr + ',"NYE")',
         '=COUNTIF(' + lr + ',1)',
         '=COUNTIF(' + lr + ',2)',
         '=COUNTIF(' + lr + ',3)',
         '=COUNTIF(' + lr + ',4)',
         '=IFERROR((COUNTIF(' + lr + ',3)+COUNTIF(' + lr + ',4))/COUNT(' + lr + '),"")']);
  });

  put([]);

  // --- By teacher --------------------------------------------------------
  put(['FEATURE PERFORMANCE BY TEACHER']);
  put(['A gap between teachers on one feature is a teaching signal. A gap on every feature is ' +
       'usually a timing or delivery difference.']);
  put(['Feature'].concat(CONFIG.teachers));
  FEATURES.forEach(function (f) {
    var crits = CRITERIA.filter(function (c) { return !c.beyond && c.feature === f; })
                        .map(function (c) { return c.crit; });
    var row = [f];
    CONFIG.teachers.forEach(function (t) {
      if (!crits.length) { row.push(''); return; }
      var terms = crits.map(function (k) {
        return 'AVERAGEIFS(' + scoreRange_(k) + ',' + teacherRange_() + ',"' +
               String(t).replace(/"/g, '""') + '")';
      });
      row.push('=IFERROR(AVERAGE(' + terms.join(',') + '),"")');
    });
    put(row);
  });

  // --- Write and format --------------------------------------------------
  var width = 8;
  sh.getRange(1, 1, rows.length, width).setValues(
    rows.map(function (x) { while (x.length < width) x.push(''); return x; })
  );

  sh.getRange(1, 1, 1, width).setFontWeight('bold').setFontSize(13);
  [4, featureLastRow + 2].forEach(function () {});
  rows.forEach(function (x, i) {
    var t = String(x[0] || '');
    if (t === t.toUpperCase() && t.length > 8 && !x[1]) {
      sh.getRange(i + 1, 1, 1, width).setFontWeight('bold').setBackground('#D9E2F3');
    }
  });

  // Percentage columns
  sh.getRange(featureFirstRow, 5, featureLastRow - featureFirstRow + 1, 3)
    .setNumberFormat('0%');
  sh.getRange(featureFirstRow, 7, featureLastRow - featureFirstRow + 1, 1)
    .setFontWeight('bold');

  // Red below 50%, amber 50-70%, on the combined feature column.
  var fRange = sh.getRange(featureFirstRow, 7, featureLastRow - featureFirstRow + 1, 1);
  var rules = sh.getConditionalFormatRules();
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenNumberLessThan(0.5).setBackground('#F4CCCC').setRanges([fRange]).build());
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenNumberBetween(0.5, 0.7).setBackground('#FCE5CD').setRanges([fRange]).build());
  sh.setConditionalFormatRules(rules);

  sh.setColumnWidth(1, 420);
  sh.setColumnWidth(8, 260);
  sh.getRange(1, 1, rows.length, width).setWrap(true).setVerticalAlignment('top');
  sh.setFrozenRows(5);

  // Column chart of feature performance.
  try {
    var chart = sh.newChart()
      .setChartType(Charts.ChartType.COLUMN)
      .addRange(sh.getRange(featureFirstRow, 1, featureLastRow - featureFirstRow + 1, 1))
      .addRange(sh.getRange(featureFirstRow, 7, featureLastRow - featureFirstRow + 1, 1))
      .setPosition(rows.length + 3, 1, 0, 0)
      .setOption('title', 'Percent earning each evidence statement feature')
      .setOption('legend', { position: 'none' })
      .setOption('vAxis', { format: 'percent', viewWindow: { min: 0, max: 1 } })
      .setOption('height', 360)
      .setOption('width', 900)
      .build();
    sh.insertChart(chart);
  } catch (e) {
    Logger.log('chart not inserted: ' + e);
  }
}

/* ============================================================ *
 *  STUDENT x FEATURE GRID
 *  One row per student, 1/0 per feature. This is the reteaching list.
 * ============================================================ */

function buildStudentFeatureGrid_(ss) {
  var sh = ss.insertSheet('Student x Feature');
  var feats = FEATURES.slice();

  var head = ['Name', 'Block', 'Teacher'].concat(feats).concat(['Features met', '% met']);
  var rows = [head];

  for (var r = ANALYSIS_FIRST_ROW; r <= ANALYSIS_LAST_ROW; r++) {
    var row = ["='Scoring'!B" + r, "='Scoring'!C" + r, "='Scoring'!D" + r];
    feats.forEach(function (f) {
      var crits = CRITERIA.filter(function (c) { return !c.beyond && c.feature === f; })
                          .map(function (c) { return c.crit; });
      if (!crits.length) { row.push(''); return; }
      var cells = crits.map(function (k) {
        return "'Scoring'!" + colLetter_(FIRST_CRIT_COL_GLOBAL + critOrder_().indexOf(k)) + r;
      });
      // Blank until every criterion for the feature is scored; then 1 only if all earned.
      row.push('=IF(COUNT(' + cells.join(',') + ')<' + crits.length + ',"",' +
               'IF(SUM(' + cells.join(',') + ')=' + crits.length + ',1,0))');
    });
    var first = colLetter_(4), last = colLetter_(3 + feats.length);
    var rr = rows.length + 1;
    row.push('=IF(A' + rr + '="","",SUM(' + first + rr + ':' + last + rr + '))');
    row.push('=IF(COUNT(' + first + rr + ':' + last + rr + ')=0,"",' +
             'AVERAGE(' + first + rr + ':' + last + rr + '))');
    rows.push(row);
  }

  sh.getRange(1, 1, rows.length, head.length).setValues(rows);
  sh.getRange(1, 1, 1, head.length).setFontWeight('bold').setWrap(true)
    .setBackground('#1F3864').setFontColor('#FFFFFF').setVerticalAlignment('top');
  sh.setFrozenRows(1);
  sh.setFrozenColumns(3);
  sh.setColumnWidth(1, 160);
  for (var c = 4; c <= 3 + feats.length; c++) sh.setColumnWidth(c, 90);
  sh.getRange(2, head.length, rows.length - 1, 1).setNumberFormat('0%');

  var grid = sh.getRange(2, 4, rows.length - 1, feats.length);
  var rules = sh.getConditionalFormatRules();
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenNumberEqualTo(0).setBackground('#F4CCCC').setRanges([grid]).build());
  rules.push(SpreadsheetApp.newConditionalFormatRule()
    .whenNumberEqualTo(1).setBackground('#E2EFDA').setRanges([grid]).build());
  sh.setConditionalFormatRules(rules);
}

/* ============================================================ *
 *  HELPERS
 * ============================================================ */

/* Criterion IDs in bucket order: the scoring sheet's column order. */
function critOrder_() {
  var out = [];
  BUCKETS.forEach(function (b) {
    b.crits.forEach(function (k) { if (out.indexOf(k) < 0) out.push(k); });
    if (b.mwdCrit && out.indexOf(b.mwdCrit) < 0) out.push(b.mwdCrit);
  });
  return out;
}

/* Evidence-statement criteria only: the denominator for the gates. */
function esCrits_() {
  return critOrder_().filter(function (k) { return !specFor_(k).beyond; });
}

/* Every bucket a criterion is tagged to. */
function bucketsFor_(crit) {
  var c = CRITERIA.filter(function (x) { return x.crit === crit; })[0];
  return (c && c.buckets) || [];
}

function specFor_(crit) {
  for (var i = 0; i < CRITERIA.length; i++) if (CRITERIA[i].crit === crit) return CRITERIA[i];
  throw new Error('No item for criterion ' + crit);
}

function correctChoice_(spec) {
  for (var i = 0; i < spec.choices.length; i++) if (spec.choices[i][1]) return spec.choices[i][0];
  throw new Error('No correct choice on ' + spec.crit);
}

/** Formula fragment that finds a response column by its question title. */
function pullExpr_(resp, row, title) {
  var safe = title.replace(/"/g, '""');
  return 'INDEX(' + resp + '!$A' + row + ':$BZ' + row +
         ',MATCH("' + safe + '",' + resp + '!$A$1:$BZ$1,0))';
}

function pull_(resp, row, title) {
  return '=IFERROR(' + pullExpr_(resp, row, title) + ',"")';
}

function colLetter_(n) {
  var s = '';
  while (n > 0) {
    var m = (n - 1) % 26;
    s = String.fromCharCode(65 + m) + s;
    n = (n - m - 1) / 26;
  }
  return s;
}
